import os
from ultralytics import YOLO

def train_and_export():
    print("Loading Yolov8-nano base model...")
    # Load a pretrained model (recommended for training)
    model = YOLO("yolov8n.pt")
    
    # Path to dataset yaml generated by convert_to_yolo.py
    data_yaml = os.path.abspath("dataset/yolo_potholes/dataset.yaml").replace('\\', '/')
    if not os.path.exists(data_yaml):
        print(f"Error: dataset.yaml not found at {data_yaml}. Run convert_to_yolo.py first.")
        return

    print("Starting Object Detection Training (YOLOv8)...")
    # Train the model using the custom dataset
    # 20 epochs is a good quick starting point to see learning, batch size auto or 16
    results = model.train(
        data=data_yaml, 
        epochs=15, 
        imgsz=224, # keep it small for quick training on CPU/basic GPU
        batch=16,
        project="civic_ai_models",
        name="pothole_detection"
    )

    print("Training finished! Evaluation metrics:")
    # Evaluate performance on validation set
    metrics = model.val()
    print("Validation mAP50-95:", metrics.box.map)

    print("Exporting model to TensorFlow.js format...")
    # Export explicitly to tfjs format for browser usage
    # Note: Ultralytics creates a folder with web_model, signature, etc.
    export_path = model.export(format="tfjs")
    
    print(f"\n====== SUCCESS ======")
    print(f"Exported model path: {export_path}")
    print(f"In your Next.js app, copy the contents of the exported folder into `public/models/potholes_od/`")

if __name__ == "__main__":
    train_and_export()
