import os
import torch
from ultralytics import YOLO

def train_and_export():
    # Force GPU usage — use dedicated NVIDIA GPU, not CPU
    if torch.cuda.is_available():
        device = 0  # First CUDA GPU
        gpu_name = torch.cuda.get_device_name(0)
        vram = torch.cuda.get_device_properties(0).total_memory / 1024**3
        print(f"\n✅ Using GPU: {gpu_name}")
        print(f"   VRAM: {vram:.1f} GB")
    else:
        device = 'cpu'
        print("\n⚠️ WARNING: No GPU detected! Training will be SLOW on CPU.")
        print("   Make sure you have NVIDIA drivers + CUDA installed.")

    print("Loading YOLOv8-nano base model...")
    model = YOLO("yolov8n.pt")
    
    # Path to combined dataset yaml generated by convert_to_yolo.py
    data_yaml = os.path.abspath("dataset/yolo_combined/dataset.yaml").replace('\\', '/')
    if not os.path.exists(data_yaml):
        print(f"Error: dataset.yaml not found at {data_yaml}. Run convert_to_yolo.py first.")
        return

    # Read class names from yaml to show what we're training on
    print(f"\nDataset config: {data_yaml}")

    print("Starting Object Detection Training (YOLOv8)...")
    results = model.train(
        data=data_yaml, 
        epochs=15, 
        imgsz=416,       # Optimized for 6GB VRAM
        batch=8,          # Smaller batch to prevent OOM on RTX 3050
        device=device,    # Force dedicated GPU
        workers=0,        # Avoid Windows multiprocessing MemoryError
        project="civic_ai_models",
        name="civic_detection"
    )

    print("Training finished! Evaluation metrics:")
    metrics = model.val()
    print("Validation mAP50-95:", metrics.box.map)

    print("Exporting model to TensorFlow.js format...")
    export_path = model.export(format="tfjs")
    
    print(f"\n====== SUCCESS ======")
    print(f"Exported model path: {export_path}")
    print(f"Copy the exported model into your Next.js project at: public/models/civic_od/")

if __name__ == "__main__":
    train_and_export()
